### ISSUE TITLE
Реализовать возможность сделать реблог записи

### ISSUE THREAD

**Issue by NickShtefan** [GolosChain/cyberSwift#2]
@NickShtefan commented on [Fri Apr 05 2019](https://github.com/GolosChain/cyber-android/issues/20)

[Documentation of ABI](https://github.com/GolosChain/golos.contracts/blob/master/golos.publication/golos.publication.abi#L690)

[Дизайн]()

**Comment by Monserg** [comment]
__Выполнено__:
 - [x] EOSTransaction: create `public struct ReblogArgs`
 - [x] EOSManager: create `static func unreg(witnessArgs:completion:)`
 - [x] RestAPIManager: create `public func unreg(witness:url:completion:)`
