### ISSUE TITLE
Реализовать метод regwitness (1)

### ISSUE THREAD

**Issue by NickShtefan** [GolosChain/cyberSwift#3]
@NickShtefan commented on [Fri Apr 05 2019](https://github.com/GolosChain/cyber-android/issues/20)

ABI

https://github.com/GolosChain/golos.contracts/blob/master/golos.ctrl/abi/golos.ctrl.abi

Последовательность:
reg -- success -- ok
vote -- success -- ok
unvote -- success -- ok
unreg -- success -- ok

**Comment by Monserg** [comment]
__Выполнено__:
 - [x] EOSTransaction: create `public struct RegwitnessArgs`
2. Logger
3. ReachabilityManager
4. RestAPIManager
5. WebSocketManager
