### ISSUE TITLE
Реализовать метод unregwitness (4)

### ISSUE THREAD

**Issue by NickShtefan** [GolosChain/cyberSwift#4]
https://github.com/GolosChain/golos.contracts/blob/master/golos.ctrl/abi/golos.ctrl.abi

Последовательность:
reg -- success -- ok
vote -- success -- ok
unvote -- success -- ok
unreg -- success -- ok

**Comment by Monserg** [comment]
__Выполнено__:
 - [x] EOSTransaction: create `public struct UnregwitnessArgs`
 - [x] EOSManager: create `static func unreg(witnessArgs:completion:)`
 - [x] RestAPIManager: create `public func unreg(witness:url:completion:)`
