### ISSUE TITLE
Реализовать метод votewitness (2)

### ISSUE THREAD

**Issue by NickShtefan** [GolosChain/cyberSwift#5]
@NickShtefan commented on [Fri Apr 05 2019](https://github.com/GolosChain/cyber-android/issues/22)

https://github.com/GolosChain/golos.contracts/blob/master/golos.ctrl/abi/golos.ctrl.abi

Последовательность:
reg -- success -- ok
vote -- success -- ok
unvote -- success -- ok
unreg -- success -- ok

**Comment by Monserg** [comment]
__Выполнено__:
 - [x] EOSTransaction: create `public struct RegwitnessArgs`
 - [x] EOSManager: create `static func reg(witnessArgs:completion:)`
 - [x] RestAPIManager: create `public func reg(witness:url:completion:)`
