### ISSUE TITLE
Реализовать метод unvotewitn (3)

### ISSUE THREAD

**Issue by NickShtefan** [GolosChain/cyberSwift#6]
https://github.com/GolosChain/golos.contracts/blob/master/golos.ctrl/abi/golos.ctrl.abi

Последовательность:
reg -- success -- ok
vote -- success -- ok
unvote -- success -- ok
unreg -- success -- ok

**Comment by Monserg** [comment]
__Выполнено__:
 - [x] EOSTransaction: create `public struct UnvotewitnessArgs`
 - [x] EOSManager: create `static func unvote(witnessArgs:completion:)`
 - [x] RestAPIManager: create `public func unvote(witness:url:completion:)`
